# .github/workflows/newsletter.yml
name: Daily Newsletter Generator

on:
  schedule:
    - cron: '0 8 * * *'  # 8 AM UTC daily
  workflow_dispatch:  # Manual trigger

jobs:
  generate-newsletter:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        pip install feedparser pandas beautifulsoup4 openai tqdm requests
    
    - name: Create newsletter directory
      run: mkdir -p newsletter
    
    - name: Run newsletter script
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        ZAPIER_WEBHOOK_URL: ${{ secrets.ZAPIER_WEBHOOK_URL }}
        GITHUB_REPOSITORY: ${{ github.repository }}
      run: python newsletter_generator.py
    
    - name: Commit and push files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add newsletter/
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Daily newsletter - $(date +'%Y-%m-%d')"
          git push
        fi